python:
  - 3.6
  - 3.7
  - 3.8
language: python
before_install:
  - sudo apt-get update
  - sudo apt-get -y install libgsl-dev
  - python --version
  - pip install -U pip
  - pip install -U pytest
  - pip install git+https://github.com/lgarrison/asdf.git
  - gcc --version
install:
  - pip install .
  - make -C pipe_asdf
script:
  - pytest
  - ./tests/test_pipe_asdf.sh
